version: '3'

services:
  webapp:
    build: .
      # context: .
      # dockerfile: Dockerfile
    image: ttwebapp
    container_name: webapp
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOSTNAME=$DB_HOSTNAME
      - DB_PORT=$DB_PORT
      - DB_DBNAME=$DB_DBNAME
    ports:
      - "49160:3000"
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    networks:
      - ttnetwork
    command: 
      npm start
      # bash -c "npm install &&npm start"
  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - "3306:3306"
    networks:
      - ttnetwork  
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
networks:
  ttnetwork:
    driver: bridge
